baseURL = "https://tutorials.groupdocs.com/watermark"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-WZTNN8"

[[deployment.targets]]
name = "Production"
URL = "s3://tutorials.groupdocs.com/?prefix=watermark/&region=us-west-2"
